version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./bin/init-mongo.sh:/init-mongo.sh
    entrypoint: [ "/init-mongo.sh" ]
