# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[db-config]
# The network chain ID
db-name = "staking-api-service"
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
address = "mongodb://localhost:27017"

[btc-config]
# Btc node host
host = "localhost:18556"
# Btc node user
user = "user"
# Btc node password
pass = "pass"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "regtest"

[remote-signer-config]
# The list of signer urls in the format http://covenant_pk@signer_host:port
urls = ["http://03f39f3ac2a85285fa821ac2bb8e50d9110decb624ff42b6af1ab8d6da902b75ca@http://127.0.0.1:9791", ]
# The timeout of each request to the remote signing server
timeout = 2s
