# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[db-config]
# The network chain ID
db-name = "staking-api-service"
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
address = "mongodb://localhost:27017"

[btc-config]
# Btc node host
host = "localhost:18556"
# Btc node user
user = "user"
# Btc node password
pass = "pass"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "regtest"

[remote-signer-config]
# The list of signer urls in the format http://covenant_pk@signer_host:port
urls = ["http://03d4625ae15c25c380e131a0a95e23612805f0f314ef5a39ff6cba2a7e3c06f5d9@http://127.0.0.1:9791", ]
# The timeout of each request to the remote signing server
timeout_seconds = 2

[metrics-config]
# Enable reporting metrics
enabled = false
# IP of the Prometheus server
host = "127.0.0.1"
# Port of the Prometheus server
port = 2112
