# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[db-config]
# The network chain ID
db-name = "staking-api-service"
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
address = "mongodb://localhost:27017"

[btc-config]
# Btc node host
host = "localhost:18556"
# Btc node user
user = "user"
# Btc node password
pass = "pass"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "regtest"

# The unsafe params configuration only for poc/mvp purposes. Storing private keys
# in the config file is not secure. After adding more secure options remove this.
[unsafe-params-config]
# The list of covenant private keys
covenant_private_keys = ["b52947dbd8c4e6447a788b3620ec1f4d06339d05d90220878e168e036729c578", ]

# The quorum of the covenants required to sign the transaction
covenant_quorum = 1
