# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[db-config]
# The network chain ID
db-name = "staking-api-service"
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
address = "mongodb://localhost:27017"
